### ISSUE TITLE
Idee

### ISSUE THREAD

**Issue by iTzPhil** [HimmelKreis4865/BetterAC#1]
Wie wäre es wenn man mehrere Punish Commandos machen könnte also z.B. /ban und noch /say Ich bin ein Hacker! oder so ähnlich.

**Comment by HimmelKreis4865** [comment]
Hallo, ja, soetwas werde ich gerne hinzufügen. 
Allerdings wäre etwas wie `/say Ich bin ein Hacker!` nicht möglich, da die Befehle von der Konsole aus gesendet werden und nicht von dem Spieler aus. 

Aber eine gute Idee

**Comment by iTzPhil** [comment]
> Hallo, ja, soetwas werde ich gerne hinzufügen.
> Allerdings wäre etwas wie `/say Ich bin ein Hacker!` nicht möglich, da die Befehle von der Konsole aus gesendet werden und nicht von dem Spieler aus.
> 
> Aber eine gute Idee

{Player} als variable ^^ /say {player} Ich hacke

**Comment by HimmelKreis4865** [comment]
Multiple punish commands wurden eingefügt, siehe neustes commit!
Daher wird dieser issue geschlossen, bei weiteren Ideen / Fragen / Problemen kannst du gerne einen neuen öffnen.
