### ISSUE TITLE
can it be used on production servers yet?

### ISSUE THREAD

**Issue by Smorted** [HimmelKreis4865/BetterAC#2]
i only want the auto click , i will disable the rest.. so is auto click good and ready for a production server?

**Comment by HimmelKreis4865** [comment]
I would recommend you to wait until this plugin finally releases, because there are still many bugs and mistakes the plugin does.

You could try autoclicker but I cannot really recommend it yet.
Will work on BetterAC today so maybe it'll be more in some hours

**Comment by HimmelKreis4865** [comment]
Just published a new dev build commit, you could try using just auto-clicker tool with this plugin.
Please test it and tell me if there are any more issues with the system or if you have any questions/suggestions 👍 
Have a great day, I will add the solved label but won't close it until you inform me that everything works fine.
