### ISSUE TITLE
Structure.BC Break: Make Module style

### ISSUE THREAD

**Issue by Blackjack200** [HimmelKreis4865/BetterAC#3]

**Comment by HimmelKreis4865** [comment]
Please give me a more detailed description of what "style" I should add. :)

**Comment by Blackjack200** [comment]
> Please give me a more detailed description of what "style" I should add. :)

like MockingBird

**Comment by HimmelKreis4865** [comment]
Uhm, could you please explain what you want to be changed? What exact style? README.md? Code cleanup?

**Comment by HimmelKreis4865** [comment]
Uhm, could you please explain what you want to be changed? What exact style? README.md? Code cleanup?
