### ISSUE TITLE
Breaking blocks where you dont have perms...

### ISSUE THREAD

**Issue by Willoxey** [HimmelKreis4865/BetterAC#5]
detects you as InstaBreak.
Steps to reproduce:
1.- Go to a protected area
2.- Try to destroy blocks
3.- Get kicked at the third time you do it.

PHP: 7.3
pmmp: 3.15.0
Latest dev build.

**Comment by Willoxey** [comment]
object(pocketmine\level\Level)#17317 (0) {
 }

I'm getting this spammed too in my console.

**Comment by HimmelKreis4865** [comment]
Hey,

Thank you for reporting those 2 bugs,

please download <a href="https://poggit.pmmp.io/ci/HimmelKreis4865/BetterAC/BetterAC"> the latest dev build </a> (or from github) again, I commited fix, please confirm that it was fixed in a quick reply. 👍  

I'd be happy if you do that.

**Comment by Willoxey** [comment]
Thank you for your fast answer.
That two issues are now fixed.
