### ISSUE TITLE
Undefined class constant return...

### ISSUE THREAD

**Issue by Willoxey** [HimmelKreis4865/BetterAC#7]
**Describe the bug**
Get internal when you try to flood.

**To Reproduce**
1. Spam on the chat
2. Internal
... It's because of the PlayerNetworkSessionAdapter.
**Expected behavior**
Getting warned for SPAM.

**Versions**
- OS: Linux
- PocketMine-MP version: 3.15.0
- PHP version: 7.3

**Additional context**
`31.08 02:57:45 [Server] Server thread/CRITICAL Error: "Undefined class constant 'return'" (EXCEPTION) in "plugins/Aletinn.phar/src/HimmelKreis4865/BetterAC/Listeners/ChatListener" at line 23
31.08 02:57:45 [Server] Server thread/CRITICAL #0 src/pocketmine/plugin/MethodEventExecutor(42): HimmelKreis4865\BetterAC\Listeners\ChatListener->onChat(object pocketmine\event\player\PlayerChatEvent)
31.08 02:57:45 [Server] Server thread/CRITICAL #1 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object HimmelKreis4865\BetterAC\Listeners\ChatListener, object pocketmine\event\player\PlayerChatEvent)
31.08 02:57:45 [Server] Server thread/CRITICAL #2 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\player\PlayerChatEvent)
31.08 02:57:45 [Server] Server thread/CRITICAL #3 src/pocketmine/Player(2315): pocketmine\event\Event->call()
31.08 02:57:45 [Server] Server thread/CRITICAL #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(131): pocketmine\Player->chat(string[1] F)
31.08 02:57:45 [Server] Server thread/CRITICAL #5 src/pocketmine/network/mcpe/protocol/TextPacket(126): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleText(object pocketmine\network\mcpe\protocol\TextPacket)
31.08 02:57:45 [Server] Server thread/CRITICAL #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
31.08 02:57:45 [Server] Server thread/CRITICAL #7 src/pocketmine/network/mcpe/protocol/BatchPacket(127): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket)
31.08 02:57:45 [Server] Server thread/CRITICAL #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(110): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
31.08 02:57:45 [Server] Server thread/CRITICAL #9 src/pocketmine/Player(3250): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
31.08 02:57:45 [Server] Server thread/CRITICAL #10 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
31.08 02:57:45 [Server] Server thread/CRITICAL #11 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[21] XXX.XXX.XXX.XXX 57219, object raklib\protocol\EncapsulatedPacket, integer 0)
31.08 02:57:45 [Server] Server thread/CRITICAL #12 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
31.08 02:57:45 [Server] Server thread/CRITICAL #13 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
31.08 02:57:45 [Server] Server thread/CRITICAL #14 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
31.08 02:57:45 [Server] Server thread/CRITICAL #15 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
31.08 02:57:45 [Server] Server thread/CRITICAL #16 src/pocketmine/Server(2157): pocketmine\snooze\SleeperHandler->sleepUntil(double 1598842665.3222)
31.08 02:57:45 [Server] Server thread/CRITICAL #17 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
31.08 02:57:45 [Server] Server thread/CRITICAL #18 src/pocketmine/Server(1588): pocketmine\Server->start()
31.08 02:57:45 [Server] Server thread/CRITICAL #19 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
31.08 02:57:45 [Server] Server thread/CRITICAL #20 src/pocketmine/PocketMine(304): pocketmine\server()
31.08 02:57:45 [Server] Server thread/CRITICAL #21 (11): require(string[103] phar:///custom-php7.3.phar/src/po)`

**Comment by HimmelKreis4865** [comment]
Thanks, I got the issue and fixed it immediately.
Thank you
